openapi: 3.0.0
info:
  title: career-level
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/career-levels:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aItems:
                    type: array
                    items:
                      $ref: ../models/Career-level.yaml
                required:
                  - aItems
      operationId: get-api-career-levels
components:
  schemas: {}
