openapi: 3.0.0
info:
  title: department
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/department/tree:
    get:
      summary: Your GET endpoint
      tags: []
      operationId: get-api-department-tree
      description: 'Получение дерево департаментов '
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aItems:
                    type: array
                    items:
                      $ref: ../models/Department-node.yaml
                required:
                  - aItems
components:
  schemas: {}
