openapi: 3.0.0
info:
  title: faq
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/faqs:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aItems:
                    type: array
                    items:
                      $ref: ../models/Faq.yaml
      operationId: get-api-faqs
components:
  schemas: {}
