openapi: 3.0.0
info:
  title: master-data
  version: '1.0'
  description: Мастер-данные
servers:
  - url: 'http://localhost:3000/masterData'
paths:
  /import:
    post:
      summary: import
      operationId: masterData-import
      responses:
        '200':
          description: OK
      description: Загрузка мастер-данных
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImportMasterDataRequestDto'
      tags:
        - masterData
    parameters: []
  /getData:
    get:
      summary: getRoles
      tags:
        - masterData
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sTitle:
                    type: string
                  oData:
                    $ref: '#/components/schemas/DataGridDto'
                required:
                  - sTitle
                  - oData
      operationId: masterData-getData
      description: Получение мастер-данных
      parameters:
        - schema:
            type: string
          in: query
          name: type
          description: Тип мастер-данных
          required: true
    parameters: []
  /export:
    get:
      summary: export
      tags: []
      responses: {}
      operationId: masterData-export
      description: Экспорт мастер-данных
      parameters:
        - schema:
            type: string
          in: query
          name: type
          description: Тип мастер-данных
          required: true
    parameters: []
  /clearData:
    post:
      summary: clearData
      operationId: post-masterData-clearData
      responses:
        '200':
          description: OK
      description: Очистка всех мастер-данных
      tags:
        - masterData
    parameters: []
  /period:
    get:
      summary: getPeriod
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sStartDate:
                    type: string
                  sEndDate:
                    type: string
                required:
                  - sStartDate
                  - sEndDate
      operationId: get-getPeriod
      description: ''
    post:
      summary: ''
      operationId: post-getPeriod
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sStartDate:
                    type: string
                  sEndDate:
                    type: string
                required:
                  - sStartDate
                  - sEndDate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sStartDate:
                  type: string
                sEndDate:
                  type: string
              required:
                - sStartDate
                - sEndDate
    parameters: []
  /summary-period:
    get:
      summary: null
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sStartDate:
                    type: string
                  sEndDate:
                    type: string
                required:
                  - sStartDate
                  - sEndDate
      operationId: get-summary-period
      description: ''
    post:
      summary: ''
      operationId: post-summary-period
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sStartDate:
                    type: string
                  sEndDate:
                    type: string
                required:
                  - sStartDate
                  - sEndDate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sStartDate:
                  type: string
                sEndDate:
                  type: string
              required:
                - sStartDate
                - sEndDate
    parameters: []
  /getTimelines:
    get:
      summary: getTimelines
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimelinesDto'
      operationId: get-getTimelines
  /saveTimelines:
    post:
      summary: saveTimelines
      operationId: post-saveTimelines
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimelinesDto'
  /getLastUpdateDate:
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sLastUpdateDate:
                    type: string
                    format: YYYY-MM-DD
                    description: Дата в формате YYYY-MM-DD
                required:
                  - sLastUpdateDate
      operationId: getLastUpdateDate
      description: Получение даты последнего обновления данных (дата загрузки файла «Master data positions»)
components:
  schemas:
    DataGridDto:
      title: DataGridDto
      type: object
      description: Таблица с данными
      properties:
        aHeader:
          type: array
          description: Заголовок таблицы
          items:
            type: object
            description: Данные колонки
            properties:
              sValue:
                type: string
                description: Название колонки
            required:
              - sValue
        aRows:
          type: array
          description: Строки таблицы
          items:
            type: object
            description: Данные строки
            properties:
              aCells:
                type: array
                description: Ячейки строки
                items:
                  type: object
                  description: Данные ячейки строки
                  properties:
                    sValue:
                      type: string
                      description: Значение ячейки
            required:
              - aCells
      required:
        - aHeader
        - aRows
    ImportMasterDataRequestDto:
      title: ImportMasterDataRequestDto
      type: object
      description: Мастер-данные для импорта
      properties:
        sType:
          type: string
        sFileContent:
          type: string
          description: 'Содержимое файла, с префиксом data:text/plain;base64,'
      required:
        - sFileContent
    TimelinesDto:
      title: TimelinesDto
      type: object
      properties:
        aCycles:
          type: array
          items:
            type: object
            properties:
              sName:
                type: string
              sStart:
                type: string
              oPreparation:
                $ref: '#/components/schemas/TimelinesCyclePeriodDto'
              oPlanning:
                $ref: '#/components/schemas/TimelinesCyclePeriodDto'
              oProcessing:
                $ref: '#/components/schemas/TimelinesCyclePeriodDto'
            required:
              - sName
              - sStart
              - oPreparation
              - oPlanning
              - oProcessing
      required:
        - aCycles
    TimelinesCyclePeriodDto:
      title: TimelinesCyclePeriodDto
      type: object
      properties:
        sStartDate:
          type: string
          description: Дата в формате YYYY-MM-DD
          format: date
        sEndDate:
          type: string
          description: Дата в формате YYYY-MM-DD
          format: date
