openapi: 3.0.0
info:
  title: notification
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/notifications/activity-feed:
    post:
      summary: ''
      operationId: post-api-activity-feed
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aNotifications:
                    $ref: ../models/Notification.yaml
                  aActionTypes:
                    type:
                      - string
                      - array
                    items:
                      $ref: ./summary.yaml#/components/schemas/IdStringList
                required:
                  - aNotifications
                  - aActionTypes
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivityFeedFilters'
        description: ''
    parameters: []
  /api/notifications:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Notification.yaml
      operationId: get-api-notifications
components:
  schemas:
    ActivityFeedFilters:
      title: ActivityFeedFilters
      type: object
      properties:
        aPositionIds:
          type: array
          items:
            type: number
        sPeriod:
          type: string
          enum:
            - LastHour
            - LastDay
            - LastWeek
            - LastMonth
            - Customised
        sDateFrom:
          type: string
        sDateTo:
          type: string
        aActionTypes:
          type: array
          items:
            type: string
        sSearch:
          type: string
      required:
        - aPositionIds
