openapi: 3.0.0
info:
  title: offices
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/offices:
    get:
      summary: null
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aItems:
                    type: array
                    items:
                      $ref: ../models/Office.yaml
                required:
                  - aItems
      operationId: get-api-offices
components:
  schemas: {}
