openapi: 3.0.0
info:
  title: office
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/office:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aItems:
                    type: array
                    items:
                      $ref: '#/components/schemas/office'
      operationId: get-api-office
      description: Получение списка офисов
components:
  schemas:
    office:
      title: office
      type: object
      properties:
        iId:
          type: number
        sName:
          type: string
      required:
        - iId
        - sName
