openapi: 3.0.0
info:
  title: participant
  version: '1.0'
  description: Участники планирования
servers:
  - url: 'http://localhost:3000/participant'
paths:
  /setAccess:
    post:
      summary: setAccess
      operationId: post-participant-setAccess
      responses:
        '200':
          description: OK
      description: Установка доступа для сотрудника
      tags:
        - manageParticipants
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                iParticipantGroupId:
                  type: number
                bHasAccess:
                  type: boolean
              required:
                - iParticipantGroupId
                - bHasAccess
        description: ''
    parameters: []
  /setPermissions:
    post:
      summary: setPermissions
      operationId: post-participant-setPermissions
      responses:
        '200':
          description: OK
      description: Установка прав для сотрудника
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                iParticipantId:
                  type: number
                sPermissions:
                  type: string
                  enum:
                    - canView
                    - canEdit
              required:
                - iParticipantId
                - sPermissions
      tags:
        - manageParticipants
    parameters: []
  /setDueDate:
    post:
      summary: setDueDate
      operationId: post-participant-setDueDate
      responses:
        '200':
          description: OK
      description: Установка срока действия для сотрудника
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                iParticipantId:
                  type: number
                sDueDate:
                  type: string
                  description: YYYY-MM-DD
              required:
                - iParticipantId
                - sDueDate
        description: ''
      tags:
        - manageParticipants
    parameters: []
  /setNotification:
    post:
      summary: setNotification
      operationId: post-participant-setNotification
      responses:
        '200':
          description: OK
      description: Установка уведомления для сотрудника
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                iParticipantId:
                  type: number
                sNotification:
                  type: string
                  enum:
                    - dontNotify
                    - sendEmail
              required:
                - iParticipantId
                - sNotification
      tags:
        - manageParticipants
    parameters: []
  '/{iId}/saveExcludeEmployee':
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
    post:
      summary: ''
      operationId: post-iId-saveExcludeEmployee
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: number
      description: ''
  '/{iId}/employeeForExclude':
    parameters:
      - schema:
          type: string
        name: iId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Employee-short.yaml
      operationId: get-iId-employeeForExclude
      parameters:
        - schema:
            type: string
          in: query
          name: sText
          required: true
components:
  schemas: {}
