openapi: 3.0.0
info:
  title: payment-frequencies
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/payment-frequencies:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aItems:
                    type: array
                    items:
                      $ref: ../models/Payment-frequency.yaml
      operationId: get-api-payment-frequencies
components:
  schemas: {}
