openapi: 3.0.0
info:
  title: positions
  version: '1.0'
  description: Позиции
servers:
  - url: 'http://localhost:3000'
paths:
  /api/positions:
    get:
      summary: Получение списка должностей
      tags: []
      responses: {}
      operationId: get-positions
      description: Возвращает список должностей по переданным параметрам
      parameters:
        - schema:
            type: number
          in: query
          name: iReportingFunctionId
          description: ''
        - schema:
            type: array
          in: query
          name: aOfficeIds
        - schema:
            type: array
          in: query
          name: aDepartmentIds
        - schema:
            type: array
          in: query
          name: aManagerIds
        - schema:
            type: string
            enum:
              - Active Employee
              - Vacancy
          in: query
          name: sCurrentStatus
          description: Статус должности
        - schema:
            type: string
          in: query
          name: sText
          description: 'Пользовательский ввод. Искоть совпадение по полям sCode, sName, sAssignee'
        - schema:
            type: array
          in: query
          name: sSort
          description: "поля по котрым нужно сортировать.\nВсе возможные значения:\n[ sName, \n  sCareerLevel, \n  sStartDateASC,\n  sStartDateDESC,\n  sCurrentStatus,\n  office,\n  sFullOrgPath,\n  sEmployeeClass,\n  sAssignee,\n  salaryASC,\n  salaryDESC\n]"
        - schema:
            type: number
          in: query
          name: iDepartmentId
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                aPositions:
                  type: array
                  items:
                    $ref: ../models/Position.yaml
                aManagers:
                  type: array
                  items:
                    $ref: ../models/Manager.yaml
                aOffices:
                  type: array
                  items:
                    $ref: ../models/Office.yaml
                aDepartments:
                  type: array
                  items:
                    $ref: ../models/Department-node.yaml
                aParticipants:
                  type: array
                  items:
                    $ref: ../models/Participant-short.yaml
          application/xml:
            schema:
              type: object
              properties:
                aItems:
                  type: array
                  items:
                    type: object
                    properties:
                      iId:
                        type: number
                      sName:
                        type: string
                      sType:
                        type: string
                      oOffice:
                        type: object
                      oDepartment:
                        type: object
                      managers:
                        type: array
                        items:
                          type: object
                '':
                  type: string
        description: |-
          [
          ]
    parameters: []
    post:
      summary: ''
      operationId: post-api-positions
      responses:
        '200':
          description: OK
      description: Добавление
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Vacancy-adding.yaml
        description: ''
  '/api/positions/{iId}':
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-positions-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Position.yaml
      description: Получения одной позоции
    put:
      summary: ''
      operationId: put-api-positions-iId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position.yaml
      description: Изменение должности
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Vacancy-adding.yaml
  '/api/positions/{iId}/inactive':
    post:
      summary: ''
      operationId: post-api-positions-inactive
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Inactive.yaml
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
  '/api/positions/{iId}/long-leave':
    post:
      summary: ''
      operationId: post-api-positions-long-leave
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Long-leave.yaml
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
  '/api/positions/{iId}/future-replacement':
    post:
      summary: ''
      operationId: post-api-positions-future-replacement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Future-replacement.yaml
        description: ''
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
  '/api/positions/{iId}/comment':
    post:
      summary: ''
      operationId: post-api-positions-comment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sComment:
                  type: string
              required:
                - sComment
        description: ''
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
  '/api/positions/{iId}/salary-change':
    post:
      summary: ''
      operationId: post-api-positions-salary-change
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Salary-change-adding.yaml
        description: ''
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
  '/api/positions/{iId}/start-date':
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
    post:
      summary: ''
      operationId: post-api-positions-iId-start-date
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: string
      description: Изменение поле sStartDate в позиции
  '/api/position/{iId}/return-from-long-leave':
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
    post:
      summary: ''
      operationId: post-api-position-iId-return-from-long-leave
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Return-from-long-leave.yaml
  /api/positions/add:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aVacancyTypes:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aEmployeeClasses:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aJobFamilies:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aCareers:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aChangeReasons:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aOffices:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
        '':
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-api-positions-add
      parameters:
        - schema:
            type: number
          in: query
          name: reportingFunctionId
          required: true
  /api/positions/update:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aVacancyTypes:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aEmployeeClasses:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aJobFamilies:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aCareers:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aChangeReasons:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aOffices:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
      operationId: get-api-positions-update
      parameters:
        - schema:
            type: number
          in: query
          name: reportingFunctionId
          required: true
        - schema:
            type: number
          in: query
          name: positionId
          required: true
  /api/positions/cost-center:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Catalog.yaml
      operationId: get-api-positions-cost-center
      parameters:
        - schema:
            type: string
          in: query
          name: office
          required: true
        - schema:
            type: string
          in: query
          name: positionId
          description: передается если на изменение
  /api/positions/department:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Catalog.yaml
      operationId: get-api-positions-department
      parameters:
        - schema:
            type: string
          in: query
          name: office
          required: true
        - schema:
            type: string
          in: query
          name: costCenter
          required: true
        - schema:
            type: string
          in: query
          name: positionId
          description: передается если на изменение
      description: ''
components:
  schemas: {}
