openapi: 3.0.0
info:
  title: positions
  version: '1.0'
  description: Позиции
servers:
  - url: 'http://localhost:3000'
paths:
  /positions:
    get:
      summary: GET Postions
      tags: []
      responses: {}
      operationId: get-positions
      description: Получение позици
      parameters:
        - schema:
            type: string
          in: query
          name: sOffice
        - schema:
            type: string
          in: query
          name: aDepartmentCode
        - schema:
            type: array
          in: query
          name: aParticipantsIds
        - schema:
            type: string
            enum:
              - Active Employees
              - Long Leaves
              - Vacancies
          in: query
          name: sType
          description: Типы позиции
        - schema:
            type: string
          in: query
          name: sText
          description: ''
        - schema:
            type: array
          in: query
          name: aSort
          description: |-
            массив полей по которым нужно сортировать
            например: [-sName, +oDepartment ...]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                aItems:
                  type: array
                  items:
                    $ref: ../models/Position.yaml
          application/xml:
            schema:
              type: object
              properties:
                aItems:
                  type: array
                  items:
                    type: object
                    properties:
                      iId:
                        type: number
                      sName:
                        type: string
                      sType:
                        type: string
                      oOffice:
                        type: object
                      oDepartment:
                        type: object
                      managers:
                        type: array
                        items:
                          type: object
                '':
                  type: string
        description: |-
          [
          ]
  '/positions/{iId}':
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-positions-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Position.yaml
      description: Получения одной позоции
  /positions/:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-positions
    post:
      summary: ''
      operationId: post-positions
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/position-adding.yaml
components:
  schemas: {}
