openapi: 3.0.0
info:
  title: positions
  version: '1.0'
  description: Позиции
servers:
  - url: 'http://localhost:3000'
paths:
  /api/positions:
    get:
      summary: Получение списка должностей
      tags: []
      responses: {}
      operationId: get-positions
      description: Возвращает список должностей по переданным параметрам
      parameters:
        - schema:
            type: number
          in: query
          name: iReportingFunctionId
          description: ''
        - schema:
            type: array
          in: query
          name: aOfficeIds
        - schema:
            type: array
          in: query
          name: aDepartmentIds
        - schema:
            type: array
          in: query
          name: aManagerIds
        - schema:
            type: string
            enum:
              - Active Employee
              - Vacancy
          in: query
          name: sCurrentStatus
          description: Статус должности
        - schema:
            type: string
          in: query
          name: sText
          description: 'Пользовательский ввод. Искоть совпадение по полям sCode, sName, sAssignee'
        - schema:
            type: array
          in: query
          name: sSort
          description: "поля по котрым нужно сортировать.\nВсе возможные значения:\n[ sName, \n  sCareerLevel, \n  sStartDateASC,\n  sStartDateDESC,\n  sCurrentStatus,\n  office,\n  sFullOrgPath,\n  sEmployeeClass,\n  sAssignee,\n  salaryASC,\n  salaryDESC\n]"
        - schema:
            type: number
          in: query
          name: iDepartmentId
        - schema:
            type: boolean
          in: query
          name: bOnlyInactive
        - schema:
            type: boolean
          in: query
          name: bOnlySalaryUpdates
        - schema:
            type: boolean
          in: query
          name: bOnlyUpdates
        - schema:
            type: array
          in: query
          name: aCostCenters
        - schema:
            type: array
          in: query
          name: aSubmissionStatuses
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                aPositions:
                  type: array
                  items:
                    $ref: ../models/Position-short.yaml
                aManagers:
                  type: array
                  items:
                    $ref: ../models/Manager.yaml
                aOffices:
                  type: array
                  items:
                    $ref: ../models/Office.yaml
                aDepartments:
                  type: array
                  items:
                    $ref: ../models/Department-node.yaml
                aParticipants:
                  type: array
                  items:
                    $ref: ../models/Participant-short.yaml
                aCostCenters:
                  type: array
                  items:
                    type: object
                    properties:
                      sId:
                        type: string
                      sName:
                        type: string
                    required:
                      - sId
                      - sName
              required:
                - aPositions
                - aManagers
                - aOffices
                - aDepartments
                - aParticipants
                - aCostCenters
          application/xml:
            schema:
              type: object
              properties:
                aItems:
                  type: array
                  items:
                    type: object
                    properties:
                      iId:
                        type: number
                      sName:
                        type: string
                      sType:
                        type: string
                      oOffice:
                        type: object
                      oDepartment:
                        type: object
                      managers:
                        type: array
                        items:
                          type: object
                '':
                  type: string
        description: |-
          [
          ]
    parameters: []
    post:
      summary: ''
      operationId: post-api-positions
      responses:
        '200':
          description: OK
      description: Добавление
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Vacancy-adding.yaml
        description: ''
  '/api/positions/{iId}':
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-positions-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Position.yaml
      description: Получения одной позоции
    put:
      summary: ''
      operationId: put-api-positions-iId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position.yaml
      description: Изменение должности
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Vacancy-adding.yaml
  /api/positions/inactive:
    post:
      summary: ''
      operationId: post-api-positions-inactive
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Position-short.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                aPositionsIds:
                  type: array
                  items:
                    type: number
                oInactive:
                  $ref: ../models/Inactive.yaml
              required:
                - aPositionsIds
                - oInactive
    parameters: []
  '/api/positions/{iId}/long-leave':
    post:
      summary: ''
      operationId: post-api-positions-long-leave
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position-short.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Long-leave.yaml
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
  '/api/positions/{iId}/future-replacement':
    post:
      summary: ''
      operationId: post-api-positions-future-replacement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position-short.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Future-replacement.yaml
        description: ''
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
  '/api/positions/{iId}/comment':
    post:
      summary: ''
      operationId: post-api-positions-comment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position-short.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sComment:
                  type: string
              required:
                - sComment
        description: ''
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
  '/api/positions/{iId}/salary-change':
    post:
      summary: ''
      operationId: post-api-positions-salary-change
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position-short.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Salary-change-adding.yaml
        description: ''
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
  /api/positions/start-date:
    parameters: []
    post:
      summary: ''
      operationId: post-api-positions-iId-start-date
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Position-short.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                aPositionsIds:
                  type: array
                  items:
                    type: number
                oStartDate:
                  $ref: ../models/Start-date.yaml
              required:
                - aPositionsIds
                - oStartDate
      description: Изменение поле sStartDate в позиции
  '/api/position/{iId}/return-from-long-leave':
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
    post:
      summary: ''
      operationId: post-api-position-iId-return-from-long-leave
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position-short.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Return-from-long-leave.yaml
  /api/positions/add:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aVacancyTypes:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aEmployeeClasses:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aJobFamilyGroups:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aCareers:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aChangeReasons:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aOffices:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
        '':
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-api-positions-add
      parameters:
        - schema:
            type: number
          in: query
          name: reportingFunctionId
  /api/positions/update:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aVacancyTypes:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aEmployeeClasses:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aJobFamilyGroups:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aCareers:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aChangeReasons:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
                  aOffices:
                    type: array
                    items:
                      $ref: ../models/Catalog.yaml
      operationId: get-api-positions-update
      parameters:
        - schema:
            type: number
          in: query
          name: reportingFunctionId
          required: true
        - schema:
            type: number
          in: query
          name: positionId
          required: true
  /api/positions/cost-center:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Catalog.yaml
      operationId: get-api-positions-cost-center
      parameters:
        - schema:
            type: string
          in: query
          name: office
          required: true
        - schema:
            type: string
          in: query
          name: positionId
          description: передается если на изменение
  /api/positions/department:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Catalog.yaml
      operationId: get-api-positions-department
      parameters:
        - schema:
            type: string
          in: query
          name: office
          required: true
        - schema:
            type: string
          in: query
          name: costCenter
          required: true
        - schema:
            type: string
          in: query
          name: positionId
          description: передается если на изменение
      description: ''
  /api/positions/change-reasons:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aItems:
                    type: array
                    items:
                      type: object
                      properties:
                        sValue:
                          type: string
                        sText:
                          type: string
                      required:
                        - sValue
                        - sText
      operationId: get-api-positions-change-reasons
  '/api/positions/{iId}/salary-change/{iSalaryChangeId}':
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
      - schema:
          type: number
        name: iSalaryChangeId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Salary-change.yaml
      operationId: get-api-positions-iId-salary-change-iSalaryChangeId
      description: ''
    put:
      summary: ''
      operationId: put-api-positions-iId-salary-change-iSalaryChangeId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Salary-change-adding.yaml
        description: ''
    delete:
      summary: ''
      operationId: delete-api-positions-iId-salary-change-iSalaryChangeId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Position-short.yaml
  /api/positions/job-family:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Catalog.yaml
      operationId: get-api-positions-job-family
      parameters:
        - schema:
            type: string
          in: query
          name: sJobFamilyGroup
          required: true
        - schema:
            type: string
          in: query
          name: iPositionId
  /api/positions/job-sub-family:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Catalog.yaml
      operationId: get-api-positions-job-sub-family
      parameters:
        - schema:
            type: string
          in: query
          name: sJobFamilyGroup
          required: true
        - schema:
            type: string
          in: query
          name: sJobFamily
          required: true
        - schema:
            type: string
          in: query
          name: iPositionId
  '/api/positions/{iId}/actions':
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
    get:
      summary: ''
      operationId: get-api-positions-iId-actions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Position-action.yaml
  /api/positions/approve-and-submit:
    post:
      summary: ''
      operationId: post-api-positions-approve-and-submit
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: number
        description: передается iId позиции
  /api/positions/export-to-excel:
    post:
      summary: ''
      operationId: post-api-positions-export-to-excel
      responses:
        '200':
          description: OK
      description: Возвращать excel file. Здесь нету возможности описывать файл
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: number
  /api/positions/return-to-edit:
    post:
      summary: ''
      operationId: post-api-positions-return-to-edit
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: number
      responses:
        '200':
          description: OK
  '/api/positions/employee-avatar/{sEmployeeId}':
    parameters:
      - schema:
          type: string
        name: sEmployeeId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-api-positions-employee-avatar-iEmployeeId
      description: Получение фотографии соотрудника
components:
  schemas: {}
