openapi: 3.0.0
info:
  title: positions
  version: '1.0'
  description: Позиции
servers:
  - url: 'http://localhost:3000'
paths:
  /api/positions:
    get:
      summary: Получение списка должностей
      tags: []
      responses: {}
      operationId: get-positions
      description: Возвращает список должностей по переданным параметрам
      parameters:
        - schema:
            type: number
          in: query
          name: iReportingFunctionId
          description: ''
          required: true
        - schema:
            type: array
          in: query
          name: aOfficeIds
        - schema:
            type: array
          in: query
          name: aDepartmentIds
        - schema:
            type: array
          in: query
          name: aManagerIds
        - schema:
            type: string
            enum:
              - Active Employee
              - Vacancy
          in: query
          name: sCurrentStatus
          description: Статус должности
        - schema:
            type: string
          in: query
          name: sText
          description: 'Пользовательский ввод. Искоть совпадение по полям sCode, sName, sAssignee'
        - schema:
            type: number
          in: query
          name: iCurrencyId
          description: id валюты на которую нужно конвертировать ЗП сотрудников
        - schema:
            type: number
          in: query
          name: iPaymentFrequencyId
          description: id Частоты Оплаты
        - schema:
            type: array
          in: query
          name: aSort
          description: "поля по котрым нужно сортировать.\nВсе возможные значения:\n[ sName, \n  sCareerLevel, \n  sStartDateASC,\n  sStartDateDESC,\n  sCurrentStatus,\n  office,\n  sFullOrgPath,\n  sEmployeeClass,\n  sAssignee,\n  salaryASC,\n  salaryDESC\n]"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                aItems:
                  type: array
                  items:
                    $ref: ../models/Position.yaml
          application/xml:
            schema:
              type: object
              properties:
                aItems:
                  type: array
                  items:
                    type: object
                    properties:
                      iId:
                        type: number
                      sName:
                        type: string
                      sType:
                        type: string
                      oOffice:
                        type: object
                      oDepartment:
                        type: object
                      managers:
                        type: array
                        items:
                          type: object
                '':
                  type: string
        description: |-
          [
          ]
    parameters: []
  '/api/positions/{iId}':
    parameters:
      - schema:
          type: number
        name: iId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-positions-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Position.yaml
      description: Получения одной позоции
components:
  schemas: {}
