openapi: 3.0.0
info:
  title: Resource planning backend
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users/authenticate:
    post:
      summary: authenticate
      operationId: post-users-authenticate
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sLogin:
                  type: string
                sPassword:
                  type: string
              required:
                - sLogin
                - sPassword
            examples: {}
        description: ''
      description: Авторизация пользователя по логину и паролю
      tags:
        - users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - properties:
                      sUserName:
                        type: string
                        description: Имя пользователя для заголовка
                      sToken:
                        type: string
                        description: Токен JWT
                      sRefreshToken:
                        type: string
                        description: Токен JWT
                    required:
                      - sUserName
                      - sToken
                      - sRefreshToken
                  - properties:
                      sError:
                        type: string
                        description: Текст причины неуспешной авторизации
                    required:
                      - sError
                type: object
  /users/refreshToken:
    post:
      summary: refreshToken
      operationId: post-users-refreshToken
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sToken:
                    type: string
                  sRefreshToken:
                    type: string
                required:
                  - sToken
                  - sRefreshToken
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sToken:
                  type: string
                sRefreshToken:
                  type: string
              required:
                - sToken
                - sRefreshToken
      tags:
        - users
      description: Обновление токена авторизации
components:
  schemas: {}
