openapi: 3.0.0
info:
  title: saml
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/saml/getSsoLoginPage:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-api-saml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sLoginUrl:
                  type: string
              required:
                - sLoginUrl
    parameters: []
components:
  schemas: {}
